"""
markets_config.py - auto-generated by build_config.py

Generated 2026-05-06T03:50:55.453246+00:00 from live Polymarket Gamma API.
  Tier A (<=14d, eligible): 3 markets
  Tier B (14-30d, near):    8 markets
  Tier C (30-90d, mid):     8 markets

All markets verified against /events/slug/<slug> before inclusion -
they should bind cleanly on backend startup. The 14-day eligibility
threshold (set in pinning.py) means Tier A markets populate the
GOF comparison; Tier B/C render as 'Calibrating'.
"""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional


@dataclass
class OIECConfig:
    idx: int
    name: str
    poly_slug:     Optional[str] = None
    poly_outcome:  str = "Yes"
    kalshi_query:  Optional[str] = None
    kalshi_ticker: Optional[str] = None
    tau_years: float = 0.25
    ttr_years: float = 1.0
    primary: str = "polymarket"
    scheduled_events: list[tuple[str, str]] = field(default_factory=list)


MARKETS: list[OIECConfig] = [

    # ============================================================
    # TIER A - eligible markets (TTR <= 14 days)
    # These will populate the GOF performance comparison.
    # ============================================================

    OIECConfig(
        idx=0,
        name="Will Jared Hudson be the Republican nominee for Senate in Alabama?",
        primary="polymarket",
        poly_slug="alabama-republican-senate-primary-winner",
        poly_outcome="Jared Hudson",
        kalshi_query=None,
        kalshi_ticker=None,
        ttr_years=0.0352,          # ~12.8 days, vol24h=$267
        tau_years=0.0176,
        scheduled_events=[],
    ),
    OIECConfig(
        idx=1,
        name="Will Mark Wheeler be the Democratic nominee for Senate in Alabama?",
        primary="polymarket",
        poly_slug="alabama-democratic-senate-primary-winner",
        poly_outcome="Mark Wheeler",
        kalshi_query=None,
        kalshi_ticker=None,
        ttr_years=0.0352,          # ~12.8 days, vol24h=$161
        tau_years=0.0176,
        scheduled_events=[],
    ),
    OIECConfig(
        idx=2,
        name="Will Earl Carter be the Republican nominee for Senate in Georgia?",
        primary="polymarket",
        poly_slug="georgia-republican-senate-primary-winner",
        poly_outcome="Earl Carter",
        kalshi_query=None,
        kalshi_ticker=None,
        ttr_years=0.0352,          # ~12.8 days, vol24h=$106
        tau_years=0.0176,
        scheduled_events=[],
    ),

    # ============================================================
    # TIER B - near-resolution markets (14-30 days)
    # ============================================================

    OIECConfig(
        idx=3,
        name="Will Arsenal win the 2025–26 Champions League?",
        primary="polymarket",
        poly_slug="uefa-champions-league-winner",
        poly_outcome="Arsenal",
        kalshi_query=None,
        kalshi_ticker=None,
        ttr_years=0.0680,          # ~24.8 days, vol24h=$425,355
        tau_years=0.0340,
        scheduled_events=[],
    ),
    OIECConfig(
        idx=4,
        name="Will Chung Jin-suk win the 2026 Chungcheongnam Province gubernatorial election?",
        primary="polymarket",
        poly_slug="chungcheongnam-province-governor-election-winner",
        poly_outcome="Chung Jin-suk",
        kalshi_query=None,
        kalshi_ticker=None,
        ttr_years=0.0762,          # ~27.8 days, vol24h=$154,170
        tau_years=0.0381,
        scheduled_events=[],
    ),
    OIECConfig(
        idx=5,
        name="Will Luis Gilberto Murillo win the 1st round of the 2026 Colombian presidential election?",
        primary="polymarket",
        poly_slug="colombia-presidential-election-1st-round-winner",
        poly_outcome="Luis Gilberto Murillo",
        kalshi_query=None,
        kalshi_ticker=None,
        ttr_years=0.0698,          # ~25.5 days, vol24h=$58,663
        tau_years=0.0349,
        scheduled_events=[],
    ),
    OIECConfig(
        idx=6,
        name="Will Manchester City win the 2025–26 English Premier League?",
        primary="polymarket",
        poly_slug="english-premier-league-winner",
        poly_outcome="Man City",
        kalshi_query=None,
        kalshi_ticker=None,
        ttr_years=0.0571,          # ~20.8 days, vol24h=$51,417
        tau_years=0.0285,
        scheduled_events=[],
    ),
    OIECConfig(
        idx=7,
        name="Will Spencer Pratt win the 2026 Los Angeles mayoral election?",
        primary="polymarket",
        poly_slug="los-angeles-mayoral-election-117",
        poly_outcome="Spencer Pratt",
        kalshi_query=None,
        kalshi_ticker=None,
        ttr_years=0.0735,          # ~26.8 days, vol24h=$42,652
        tau_years=0.0367,
        scheduled_events=[],
    ),
    OIECConfig(
        idx=8,
        name="GTA VI released before June 2026?",
        primary="polymarket",
        poly_slug="gta-vi-released-before-june-2026",
        poly_outcome="Yes",
        kalshi_query=None,
        kalshi_ticker=None,
        ttr_years=0.0694,          # ~25.3 days, vol24h=$37,076
        tau_years=0.0347,
        scheduled_events=[],
    ),
    OIECConfig(
        idx=9,
        name="Will Park Ju-min win the 2026 Seoul Mayoral Election",
        primary="polymarket",
        poly_slug="2026-seoul-mayoral-election-winner",
        poly_outcome="Park Ju-min",
        kalshi_query=None,
        kalshi_ticker=None,
        ttr_years=0.0762,          # ~27.8 days, vol24h=$31,223
        tau_years=0.0381,
        scheduled_events=[],
    ),
    OIECConfig(
        idx=10,
        name="Will Ken Paxton win the 2026 Texas Republican Primary?",
        primary="polymarket",
        poly_slug="texas-republican-senate-primary-winner",
        poly_outcome="Ken Paxton",
        kalshi_query=None,
        kalshi_ticker=None,
        ttr_years=0.0543,          # ~19.8 days, vol24h=$17,381
        tau_years=0.0272,
        scheduled_events=[],
    ),

    # ============================================================
    # TIER C - mid-horizon markets (30-90 days)
    # ============================================================

    OIECConfig(
        idx=11,
        name="Will Morocco win the 2026 FIFA World Cup?",
        primary="polymarket",
        poly_slug="2026-fifa-world-cup-winner-595",
        poly_outcome="Morocco",
        kalshi_query=None,
        kalshi_ticker=None,
        ttr_years=0.2049,          # ~74.8 days, vol24h=$805,534
        tau_years=0.1024,
        scheduled_events=[],
    ),
    OIECConfig(
        idx=12,
        name="Will the Philadelphia 76ers win the 2026 NBA Finals?",
        primary="polymarket",
        poly_slug="2026-nba-champion",
        poly_outcome="Philadelphia 76ers",
        kalshi_query=None,
        kalshi_ticker=None,
        ttr_years=0.1529,          # ~55.8 days, vol24h=$440,002
        tau_years=0.0764,
        scheduled_events=[],
    ),
    OIECConfig(
        idx=13,
        name="Will Gustavo Bolívar win the 2026 Colombian presidential election?",
        primary="polymarket",
        poly_slug="colombia-presidential-election",
        poly_outcome="Yes",
        kalshi_query=None,
        kalshi_ticker=None,
        ttr_years=0.1271,          # ~46.4 days, vol24h=$136,201
        tau_years=0.0635,
        scheduled_events=[],
    ),
    OIECConfig(
        idx=14,
        name="Will Amazon be the largest company in the world by market cap on June 30?",
        primary="polymarket",
        poly_slug="largest-company-end-of-june-712",
        poly_outcome="Amazon",
        kalshi_query=None,
        kalshi_ticker=None,
        ttr_years=0.1501,          # ~54.8 days, vol24h=$129,551
        tau_years=0.0751,
        scheduled_events=[],
    ),
    OIECConfig(
        idx=15,
        name="Will the Minnesota Wild win the 2026 NHL Stanley Cup?",
        primary="polymarket",
        poly_slug="2026-nhl-stanley-cup-champion",
        poly_outcome="Minnesota Wild",
        kalshi_query=None,
        kalshi_ticker=None,
        ttr_years=0.1501,          # ~54.8 days, vol24h=$72,926
        tau_years=0.0751,
        scheduled_events=[],
    ),
    OIECConfig(
        idx=16,
        name="Will the Detroit Pistons win the NBA Eastern Conference Finals?",
        primary="polymarket",
        poly_slug="nba-playoffs-eastern-conference-champion",
        poly_outcome="Detroit Pistons",
        kalshi_query=None,
        kalshi_ticker=None,
        ttr_years=0.1118,          # ~40.8 days, vol24h=$37,756
        tau_years=0.0559,
        scheduled_events=[],
    ),
    OIECConfig(
        idx=17,
        name="Will Victor Wembanyama win the 2025–2026 NBA MVP?",
        primary="polymarket",
        poly_slug="nba-mvp-694",
        poly_outcome="Victor Wembanyama",
        kalshi_query=None,
        kalshi_ticker=None,
        ttr_years=0.0954,          # ~34.8 days, vol24h=$35,750
        tau_years=0.0477,
        scheduled_events=[],
    ),
    OIECConfig(
        idx=18,
        name="Will the Los Angeles Lakers win the NBA Western Conference Finals?",
        primary="polymarket",
        poly_slug="nba-playoffs-western-conference-champion",
        poly_outcome="Los Angeles Lakers",
        kalshi_query=None,
        kalshi_ticker=None,
        ttr_years=0.1118,          # ~40.8 days, vol24h=$35,373
        tau_years=0.0559,
        scheduled_events=[],
    ),

]
